### ISSUE TITLE
Panic with version 1.5.3

### ISSUE THREAD

**Issue by Schmiddiii** [smol-rs/async-executor#54]
An `cargo update` updated `async-executor` to version 1.5.3 from 1.5.1. Since this update, I am getting the attached panic when running  my application. Note that when pinning back to 1.5.1 and keeping all other crates the same, this panic does not happen.

I don't have a  minimal reproducible exampe as I don't know how to use this crate (I just use it as a transitive dependency in `ashpd > async-std > async-global-executor > async-executor` and `ashpd > zbus > async-executor`). The full code I use it in is [here](https://gitlab.com/schmiddi-on-mobile/flare/-/merge_requests/93/diffs?commit_id=4d54e3cc0f8765ad922c2072e0d031f0a37d806b).

<details>
<summary>The Panic</summary>

```
thread 'tokio-runtime-worker' panicked at 'missing local queue', /path/to/flare/build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.3/src/lib.rs:918:57
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: core::option::Option<T>::expect
             at /build/rustc-1.71.1-src/library/core/src/option.rs:898:21
   4: async_executor::LocalQueue::with::<impl async_executor::LocalQueue>::set::{{closure}}::{{closure}}::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.3/src/lib.rs:918:43
   5: std::thread::local::LocalKey<T>::try_with
             at /build/rustc-1.71.1-src/library/std/src/thread/local.rs:270:16
   6: async_executor::LocalQueue::with::<impl async_executor::LocalQueue>::set::{{closure}}::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.3/src/lib.rs:913:21
   7: <futures_lite::future::PollFn<F> as core::future::future::Future>::poll
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:246:9
   8: async_executor::LocalQueue::with::<impl async_executor::LocalQueue>::set::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.3/src/lib.rs:936:18
   9: async_executor::Executor::run::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.3/src/lib.rs:258:10
  10: zbus::abstractions::executor::Executor::run::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/zbus-3.14.1/src/abstractions/executor.rs:118:39
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /build/rustc-1.71.1-src/library/core/src/future/future.rs:125:9
  12: zbus::connection_builder::ConnectionBuilder::build::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/zbus-3.14.1/src/connection_builder.rs:329:74
  13: zbus::connection::Connection::session::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/zbus-3.14.1/src/connection.rs:1232:47
  14: flare::dbus::feedbackd::Feedbackd::new::{{closure}}
             at ./src/dbus/feedbackd.rs:31:48
  15: flare::backend::manager::Manager::init::{{closure}}::{{closure}}
             at ./src/backend/manager.rs:341:65
  16: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  17: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  18: tokio::runtime::task::core::Core<T,S>::poll
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  19: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /build/rustc-1.71.1-src/library/core/src/panic/unwind_safe.rs:271:9
  21: std::panicking::try::do_call
             at /build/rustc-1.71.1-src/library/std/src/panicking.rs:500:40
  22: __rust_try
  23: std::panicking::try
             at /build/rustc-1.71.1-src/library/std/src/panicking.rs:464:19
  24: std::panic::catch_unwind
             at /build/rustc-1.71.1-src/library/std/src/panic.rs:142:14
  25: tokio::runtime::task::harness::poll_future
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  26: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  27: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  28: tokio::runtime::task::raw::poll
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:276:5
  29: tokio::runtime::task::raw::RawTask::poll
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  30: tokio::runtime::task::LocalNotified<S>::run
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:400:9
  31: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:576:13
  32: tokio::runtime::coop::with_budget
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  33: tokio::runtime::coop::budget
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  34: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  35: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  36: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  37: tokio::runtime::context::scoped::Scoped<T>::set
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/scoped.rs:40:9
  38: tokio::runtime::context::set_scheduler::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:26
  39: std::thread::local::LocalKey<T>::try_with
             at /build/rustc-1.71.1-src/library/std/src/thread/local.rs:270:16
  40: std::thread::local::LocalKey<T>::with
             at /build/rustc-1.71.1-src/library/std/src/thread/local.rs:246:9
  41: tokio::runtime::context::set_scheduler
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:9
  42: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  43: tokio::runtime::context::runtime::enter_runtime
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  44: tokio::runtime::scheduler::multi_thread::worker::run
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  45: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  46: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/task.rs:42:21
  47: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  48: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  49: tokio::runtime::task::core::Core<T,S>::poll
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  50: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  51: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /build/rustc-1.71.1-src/library/core/src/panic/unwind_safe.rs:271:9
  52: std::panicking::try::do_call
             at /build/rustc-1.71.1-src/library/std/src/panicking.rs:500:40
  53: __rust_try
  54: std::panicking::try
             at /build/rustc-1.71.1-src/library/std/src/panicking.rs:464:19
  55: std::panic::catch_unwind
             at /build/rustc-1.71.1-src/library/std/src/panic.rs:142:14
  56: tokio::runtime::task::harness::poll_future
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  57: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  58: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  59: tokio::runtime::task::raw::poll
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:276:5
  60: tokio::runtime::task::raw::RawTask::poll
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  61: tokio::runtime::task::UnownedTask<S>::run
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:437:9
  62: tokio::runtime::blocking::pool::Task::run
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:159:9
  63: tokio::runtime::blocking::pool::Inner::run
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:513:17
  64: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:471:13
```

</details>

**Comment by notgull** [comment]
This is caused by having two `run()` futures on the same thread, then dropping the first one and running the second one. Which isn't a common case, which is why I missed it. Should be an easy fix.
